### ISSUE TITLE
[Bug] qwerty

### ISSUE THREAD

**Issue by JonathanGun** [margunwa123/Git-practice#1]
# Anjay
test123

## Weh
https://github.com/margunwa123/Git-practice/blob/878b50037fa3c0dd661e41dd07a2e7ff627bc096/abc2.txt#L1
_Ga lulus compile ini_ @margunwa123 

## To-Do list
- [x]  makan pagi
- [ ]  makan siang
- [ ]  makan malem

### Aaand to the left
<img align="left" width="100" height="100" src="http://www.fillmurray.com/100/100">

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```
---

### Aaand to the right
<img align="right" width="100" height="100" src="http://www.fillmurray.com/100/100">

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```
---
<p align="center">
  <img width="460" height="300" src="https://i.kym-cdn.com/photos/images/newsfeed/001/488/877/20a.jpg">
</p>

<details>
<summary>Ciluk</summary>
Baaaaa
</details>

**Comment by margunwa123** [comment]
> # Anjay
> test123
> 
> ## Weh
> https://github.com/margunwa123/Git-practice/blob/878b50037fa3c0dd661e41dd07a2e7ff627bc096/abc2.txt#L1
> 
> 
> _Ga lulus compile ini_ @margunwa123
> ## To-Do list
> * [x]   makan pagi
> * [ ]   makan siang
> * [ ]   makan malem
> 
> ## Few Notes
> ### Aaand to the left
> <img alt="" width="100" height="100" src="https://camo.githubusercontent.com/8ac8115fc1d48176f64e8b1b8cbc113170726b2f/687474703a2f2f7777772e66696c6c6d75727261792e636f6d2f3130302f313030">
> 
> ```
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
> Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
> ```
> 
> ### Aaand to the right
> <img alt="" width="100" height="100" src="https://camo.githubusercontent.com/8ac8115fc1d48176f64e8b1b8cbc113170726b2f/687474703a2f2f7777772e66696c6c6d75727261792e636f6d2f3130302f313030">
> 
> ```
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
> Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
> ```
> 
> <img alt="" width="460" height="300" src="https://camo.githubusercontent.com/18612e094d999c937cf25cc8fb23b87b24cbf51e/68747470733a2f2f692e6b796d2d63646e2e636f6d2f70686f746f732f696d616765732f6e657773666565642f3030312f3438382f3837372f3230612e6a7067">
> 
> Ciluk

Bener" jo KWKWKW
